kode:
  RouteWiringMethodNaming:
    active: true
  MapperFileNaming:
    active: true
  PayloadArgumentName:
    active: true
  UseSurfaceModifier:
    active: true
  UseOnStartEmit:
    active: false
  ComponentFunctionCall:
    active: false
  BlockingSqlDelightCall:
    active: true
    sqlDelightPackage: 'app.cash.sqldelight'
  ImmutableDataClass:
    active: true
    ignoreDescendantsOf: [ "FlowEvent" ]
  MissingTypeDeclaration:
    active: false
    ignoreInClassesDerivedFrom: []
    ignoreInInterfacesDerivedFrom: []
    ignorePropertiesOfType: []
