[versions]
appQualityPlugin = "3.2.1"
kotlin = "2.4.20"
agp = "9.4.1"
detekt = "1.23.8"
ktlint = "14.2.0"
grgit = "5.3.3"
publish = "2.2.1"
junit = "6.1.3"
ktlintCli = "1.8.0"
detekt-compose-rules = "2.1.1"
detekt-rules = "2.0.0"
detekt2 = "2.0.0-alpha.6"
gradlePluginCommons = "1.0.0"
composeMultiplatform = "1.12.1"

[libraries]
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detekt-compose-rules = { module = "ru.kode:detekt-rules-compose", version.ref = "detekt-compose-rules" }
detekt-rules = { module = "ru.kode:detekt-rules", version.ref = "detekt-rules" }
detekt-rules-detekt2 = { module = "ru.kode:detekt-rules-detekt2", version.ref = "detekt-rules" }
detekt-rules-compose-detekt2 = { module = "ru.kode:detekt-rules-compose-detekt2", version.ref = "detekt-compose-rules" }
detekt-rules-ktlint-wrapper = { module = "dev.detekt:detekt-rules-ktlint-wrapper", version.ref = "detekt2" }
ktlint-cli = { module = "com.pinterest.ktlint:ktlint-cli", version.ref = "ktlintCli" }

agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
grgitCore = { module = "org.ajoberstar.grgit:grgit-core", version.ref = "grgit" }
junitBom = { module = "org.junit:junit-bom", version.ref = "junit" }
plugin-core = { group = "ru.kode.android", name = "gradle-plugin-commons", version.ref = "gradlePluginCommons" }
plugin-foundation = { group = "ru.kode.android", name = "app-quality-foundation", version.ref = "appQualityPlugin" }

kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
compose-compiler-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
compose-multiplatform-plugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "composeMultiplatform" }
ktlint-plugin = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint" }
detekt-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
detekt2-plugin = { module = "dev.detekt:detekt-gradle-plugin", version.ref = "detekt2" }

[plugins]
agp = { id = "com.android.application", version.ref = "agp" }
publish = { id = "com.gradle.plugin-publish", version.ref = "publish" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
