[versions]
appQualityPlugin = "2.0.2"
kotlin = "2.4.10"
agp = "9.3.1"
detekt = "1.23.8"
ktlint = "12.1.2"
grgit = "5.3.3"
publish = "2.1.1"
junit = "6.1.3"
ktlintCli = "1.8.0"
detekt-compose-rules = "1.4.0"
gradlePluginCommons = "1.0.0"
composeMultiplatform = "1.11.1"

[libraries]
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
detekt-compose-rules = { module = "ru.kode:detekt-rules-compose", version.ref = "detekt-compose-rules" }
ktlint-cli = { module = "com.pinterest.ktlint:ktlint-cli", version.ref = "ktlintCli" }

agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
grgitCore = { module = "org.ajoberstar.grgit:grgit-core", version.ref = "grgit" }
junitBom = { module = "org.junit:junit-bom", version.ref = "junit" }
plugin-core = { group = "ru.kode.android", name = "gradle-plugin-commons", version.ref = "gradlePluginCommons" }
plugin-foundation = { group = "ru.kode.android", name = "app-quality-foundation", version.ref = "appQualityPlugin" }

kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
compose-compiler-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
compose-multiplatform-plugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "composeMultiplatform" }
ktlint-plugin = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint" }
detekt-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }

[plugins]
agp = { id = "com.android.application", version.ref = "agp" }
publish = { id = "com.gradle.plugin-publish", version.ref = "publish" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
